export default {
  resetPassword: '重置密码',
  enterPhoneNumber: '请输入手机号',
  mobilePhoneNumber: '手机号',
  verificationCode: '验证码',
  enterVerificationCode: '请输入验证码',
  accountSecurityVerification: '账户安全验证',
  validityOfTheAccount: '为了保护账户安全，需要验证账号有效性',
  clickToGetTheVerificationCode: '点击获取验证码，输入手机号',
  getVerificationCode: '获取验证码',
  thePasswordIsDifferentTwice: '两次密码不一样！',
  newPasswordSettings: '新密码设定',
  resetAccountPassword: '请重设您的账号密码',
  enterNewLoginPassword: '请输入新的登录密码',
  noteThePasswordFormat: '注意密码格式',
  password: '密码',
  pleaseEnterThePasswordAgain: '请再次输入密码',
  confirmPassword: '确认密码',
  passwordRequirements:'密码必须为6到18位，且至少包含字母/数字/符号中的两种组合',
  twoPasswordsAreDifferent: '两次密码不一样',
  confirm: '确认',
  next: '下一步',
  followWechat: '关注微信',
  qqSupportGroup: 'QQ支持群',
  lightFastAndAccurate: '轻巧·快捷·精准',
  freeRegistrationAndUse: '免费注册使用，多渠道统一管理',
  believeInProfessionalUs: '相信专业的我们',
  contactUs: '联系我们',
  rainbowSystem: '彩虹系统',
  countdown: '倒计时',
  accountPasswordLogin: '账号密码登录',
  forgotPassword: '忘记密码',
  login: '登录'
};
